### ISSUE TITLE
Git version crashes on start

### ISSUE THREAD

**Issue by fdev31** [scorpion-26/gBar#85]
I am not able to test the latest changes from today,
I couldn't find instructions to build a debug version, so the traceback isn't super useful... tell me how I can improve that if needed:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x0000791b0a4ab393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x0000791b0a45a6c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000791b0a4424b8 in __GI_abort () at abort.c:79
#4  0x0000791b0a69ca6f in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x0000791b0a6b011c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x0000791b0a6b0189 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x0000791b0a6b03ed in __cxxabiv1::__cxa_throw
    (obj=<optimized out>, tinfo=0x791b0ac1f800 <typeinfo for Sass::Exception::OperationError>, dest=0x791b0aabdd20 <Sass::Exception::OperationError::~OperationError()>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x0000791b0aa7ded4 in Sass::File::get_cwd[abi:cxx11]() () at /usr/include/c++/13.2.1/bits/new_allocator.h:100
#9  0x0000791b0aae857c in Sass::Context::Context (this=0x64925147d370, c_ctx=..., this=<optimized out>, c_ctx=<optimized out>)
    at /usr/src/debug/libsass/libsass-3.6.6/src/context.cpp:46
#10 0x0000791b0aba661e in Sass::File_Context::File_Context (ctx=..., this=0x64925147d370) at /usr/src/debug/libsass/libsass-3.6.6/src/context.hpp:115
#11 sass_compile_file_context (file_ctx=0x64925151e3f0) at /usr/src/debug/libsass/libsass-3.6.6/src/sass_context.cpp:422
#12 0x0000649250dfbf52 in ??? ()
#13 0x0000649250da7b65 in ??? ()
#14 0x0000649250da3e6b in main ()
```

**Comment by fdev31** [comment]
Hm, it only happened once...! Closing it.
